/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Explore: typeof import('./src/components/Explore.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    Generation: typeof import('./src/components/Generation.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Explore.vue')['default']
    SignIn: typeof import('./src/components/SignIn.vue')['default']
  }
}
